#---------------------------------------------------------------
# Theme version infromation
#---------------------------------------------------------------
version: 1.0

#---------------------------------------------------------------
# Build setting
#---------------------------------------------------------------
gems: [jekyll-paginate]
# Config sass build output by sass_dir
# Config sass output is compressed or not
#
sass:
    sass_dir: /assets/stylesheet
    style: :compressed


#---------------------------------------------------------------
# Site infromation setting
#---------------------------------------------------------------

# Site
## You can create a locale setting at _locales and name *.yml
title: "Karmabhumi.org"
description: "Sayings of Indian Seers"
keywords: "Pithy"
locale: "en_IN"

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and baseurl as '/child/'
url: "bhaskar-c.github.io"
baseurl: ""
permalink: /:year/:month/:day/:title


# Pagination
plugins: [jekyll-paginate]
## Set per_page to 0 to disable pagination
paginate: 10
paginate_path: "/page:num/"


# RSS
rss:
  path: "/feed.xml"
  icon: "rss"



# Socials
## If you want the social show,place sure the social no comment
## The socials icon base font-awesome,you can learn more on http://fontawesome.io/icons/
socials:
    - name: "weibo"
      url: "http://www.weibo.com/usename/"
      icon: "weibo"
    - name: "github"
      url: "https://github.com/usename"
      icon: "github"
    - name: "facebook"
      url: "https://www.facebook.com/usename"
      icon: "facebook"

# Google analysis
google_analysus:
  enable: false
  token: "your google analysis token"
